BaSP-TG-43: Modal Form shared component
BaSP-m2022/alexis-trackgenix-app pull request #13
Opened 2022-06-07 09:15 UTC by Javier-Cervera

Some details are missing, but it is ready to start being reviewed.

2022-06-07 16:46 UTC, Javier-Cervera commented on src/Components/Shared/ModalForm/modal-form.module.css
> +  height: 550px;
Thanks for the feedback!

2022-06-07 16:48 UTC, Javier-Cervera commented on src/Components/Employees/SuccessModal/index.js
>    return props.successResponse.error === true ? (
Nice

2022-06-07 23:16 UTC, tinchorova commented
## Testing Results
Tested locally on https://alexis-trackgenix-app-git-feature-tg-43-share-427909-basp-m2022.vercel.app/

**Test Results: Failed** ⚠️

Bugs found:
1. Both add and edit modals should not have a scroll bar
![image](https://user-images.githubusercontent.com/101287875/172496638-354f4d9b-5d9c-447e-8209-b0318e7f7ec5.png)
![image](https://user-images.githubusercontent.com/101287875/172496737-6d50a009-543c-403f-9a04-291c62530448.png)
2. When on edit modal, user shouldn't be allowed to scroll the page
3. While on edit or add modal, clicking outside of the modal, holding the click and moving the cursor up or down should not select the elements of the form.
![image](https://user-images.githubusercontent.com/101287875/172497055-7b6fba1c-089f-43a2-a266-c5d94b0122ac.png)
![image](https://user-images.githubusercontent.com/101287875/172497169-bd302254-3b89-42c8-a2fa-35523381e768.png)

2022-06-07 23:18 UTC, tinchorova requested changes
Pleas refer to: https://github.com/BaSP-m2022/alexis-trackgenix-app/pull/13#issuecomment-1149261932

2022-06-09 15:43 UTC, tinchorova commented
## Testing Results
Tested locally on https://alexis-trackgenix-app-git-feature-tg-43-share-427909-basp-m2022.vercel.app/employees

**Test Results: Failed** ⚠️

Bugs found:
1. When selecting a text inside an input holding click button and releasing the click outside the modal it closes the window **(Clicking inside the modal and releasing the click outside of it, closes the modal)** dot in image shows the release position and circle represents clicking position
![image](https://user-images.githubusercontent.com/101287875/172888344-c17a7c97-c69c-4512-b526-311031f1845a.png)
2. When clicking outside the modal and going inside it closes the window. A solution for this could be to close the window on click instead of on release. Dot in image shows the release position and circle represents clicking position
![image](https://user-images.githubusercontent.com/101287875/172887748-7d47b3fc-97de-4782-8e60-bd4a09c5044f.png)

2022-06-09 15:43 UTC, tinchorova requested changes
Please refer to: https://github.com/BaSP-m2022/alexis-trackgenix-app/pull/13#issuecomment-1151298613

2022-06-09 18:15 UTC, tinchorova commented
## Test Results 

Tested locally on https://alexis-trackgenix-app-git-feature-tg-43-share-427909-basp-m2022.vercel.app/employees

**Test Results: Failed** ⚠️

Bugs found:

1. There should be more space between layers and inputs, and between each group of layer-input. A solution for this could be to create a second cloumn so that there is more space to order the elements.
![image](https://user-images.githubusercontent.com/101287875/172915239-b2697ad1-7899-4c14-8ab0-a3ec87540748.png)
2. The exit (X) button and font are too big. You could use figma's model as an example for this. Reference image below.
![image](https://user-images.githubusercontent.com/101287875/172915844-941b40e8-816d-4e6e-ba99-4b7161b72d84.png)
![image](https://user-images.githubusercontent.com/101287875/172916081-32826775-d330-451d-9e64-62ceabce3641.png)

2022-06-09 18:15 UTC, tinchorova requested changes
Please refer to https://github.com/BaSP-m2022/alexis-trackgenix-app/pull/13#issuecomment-1151447652

2022-06-09 20:51 UTC, LeonelListro commented
Test Results
Tested locally on https://alexis-trackgenix-app-git-feature-tg-43-share-427909-basp-m2022.vercel.app/employees

Test Results: Failed ⚠️

Bugs found:

1. The cross to go back on the success modal of the add and edit modal is too big.

![cross](https://user-images.githubusercontent.com/101256186/172941625-77f757b0-93f3-4737-80ba-0548291f4c6d.png)

2. The content of the password field should be hidden.

![image](https://user-images.githubusercontent.com/101256186/172941846-6327bbd4-f359-4e6a-bca5-abde47eafacd.png)

2022-06-09 21:16 UTC, LeonelListro approved these changes
Please refer to https://github.com/BaSP-m2022/alexis-trackgenix-app/pull/13#issuecomment-1151611940

2022-06-09 21:44 UTC, merged