BaSP-TG-47: Shared Components - Button
BaSP-m2022/alexis-trackgenix-app pull request #14
Opened 2022-06-07 13:44 UTC by Johsua30

Separated buttons to import in every case:
1-Button for add.
2-Button for delete.
3-Button for edit.
4-Button that recieves custom label
5-Button to close modals (not used right now)
The example buttons are used in the list and add pages of Super Admin.
The methods used so far are submit and delete.
The other buttons redirect to other pages(edit/add/back to Super Admin list).

The button to close modals has a similar template as the edit and delete buttons with transparent background and a white icon

2022-06-07 16:18 UTC, agusting19 commented on src/Components/SuperAdmins/App.jsx
>    useEffect(async () => {
useEffect can't be an async function

2022-06-07 16:19 UTC, agusting19 commented on src/Components/SuperAdmins/App.jsx
>      </Preloader>
two preloaders?

2022-06-07 16:25 UTC, agusting19 commented on src/Components/SuperAdmins/ListItem/ListItem.jsx
> +  const pencil = <FontAwesomeIcon icon={faPencil}></FontAwesomeIcon>;
As a option, const trash and const pencil maybe could be declared in the button and only send a param who tells which one to use.

2022-06-07 16:26 UTC, agusting19 reviewed
Only two things to check

2022-06-07 20:21 UTC, NicolasFontana reviewed
Except for what Agus marked for you, I see the rest quite well

2022-06-07 20:21 UTC, NicolasFontana commented on src/Components/SuperAdmins/ListItem/listItem.module.css
> +  }
This is only a comment
When the properties are repetitive, you can group them as follows:

```
.buttonEdit , .buttonDelete {
     width: 30px;
     height: 30px;
     margin: 5px;
     padding : 2px 4px 0px 4px;
     border-radius: 5px;
     color: #ffffff;
     text-align: center;
     font-family: 'Roboto', sans-serif;
     text-shadow: 2px 2px 2px grey;
     box-shadow: 2px 2px 2px rgb(78, 78, 78);
}
```

2022-06-08 01:04 UTC, NicolasFontana requested changes

2022-06-08 01:04 UTC, NicolasFontana commented on src/Components/SuperAdmins/Edit/index.js
> -  useEffect(async () => {
There is an error in the fetch. When I click on the edit button it throws me an error

This is one way to solve it:

```
const fetchData = async () => {
  try {
    const response = await fetch(`${process.env.REACT_APP_API_URL}/api/super-admins/${superAdminID}`);
    const superAdminData = await response.json();
    setsuperAdminInput({
      firstName: superAdminData.data.firstName,
      lastName: superAdminData.data.lastName,
      email: superAdminData.data.email,
      password: superAdminData.data.password,
      active: superAdminData.data.active
    });
  } catch (error) {
    console.error(error);
  }
};

useEffect(() => {
  fetchData();
}, []);
```

2022-06-08 15:41 UTC, NicolasFontana requested changes

2022-06-08 15:41 UTC, NicolasFontana commented on src/Components/SuperAdmins/super-admins.module.css
> +  box-shadow: 2px 2px 2px rgb(78, 78, 78);
You shouldn't define the button properties here, since that is done in src/Components/Shared/Buttons/button.module.css

2022-06-08 15:41 UTC, NicolasFontana commented on src/Components/SuperAdmins/ListItem/listItem.module.css
> +  }
You shouldn't define the button properties here, since that is done in src/Components/Shared/Buttons/button.module.css

2022-06-08 15:41 UTC, NicolasFontana commented on src/Components/SuperAdmins/Add/add.module.css
>  }
You shouldn't define the button properties here, since that is done in src/Components/Shared/Buttons/button.module.css

2022-06-08 15:52 UTC, NicolasFontana commented
To prevent the styles you used from being stepped on, you can remove the global property that is defined with * found in src/Components/Tasks/ListItem/listItem.module.css

2022-06-08 16:29 UTC, Javier-Cervera commented on src/Components/Shared/Buttons/button.module.css
> +    color: #000000;
For text we could use #373867 instead

2022-06-09 21:41 UTC, LeonelListro commented
## Test Results

Tested locally on https://alexis-trackgenix-app-git-feature-tg-47-share-28bbcf-basp-m2022.vercel.app/

**Test Results**: Failed ⚠️

Bugs found:

1. Cancel button should be always on the left side (according to material.io conventions).

![Sin título](https://user-images.githubusercontent.com/101256186/172948056-2a0b474d-ef7f-4254-8212-21a65ccdc56a.png)
![Sin título](https://user-images.githubusercontent.com/101256186/172948386-2e550ff7-3169-4e6c-a302-c109f8fe446f.png)

2.  Button "Save" should have a border line like the "Cancel" button.

![Sin título](https://user-images.githubusercontent.com/101256186/172948573-3bc2e79b-6f74-4358-b51c-4531d3ce15ae.png)

2022-06-09 21:42 UTC, LeonelListro requested changes
please refer to https://github.com/BaSP-m2022/alexis-trackgenix-app/pull/14#issuecomment-1151651927

2022-06-09 21:58 UTC, LeonelListro approved these changes
Good job!

2022-06-09 22:19 UTC, merged