BaSP-TG-44: Shared Componentes Success/Error Modal
BaSP-m2022/alexis-trackgenix-app pull request #17
Opened 2022-06-07 23:50 UTC by AlejoGF

2022-06-08 14:14 UTC, agusting19 reviewed
Only one thing to correct. The rest seems to be nice

2022-06-08 15:28 UTC, Javier-Cervera commented on src/Components/Employees/index.js
> +import Table from '../Shared/Table/Table';
I understand from how it's implemented that it needs a working modal, and that modal needs a list/table.

Maybe we could merge it after the table and modal form.

2022-06-08 16:19 UTC, agusting19 commented on src/Components/Employees/index.js
> +import Table from '../Shared/Table/Table';
It is well implemented, it just does not seem like good practice to me.
But you're right, we can implement it after merging the table.

2022-06-08 16:36 UTC, Javier-Cervera approved these changes
Ready for QA!

2022-06-09 17:38 UTC, lucianofrailelopez approved these changes

2022-06-09 22:10 UTC, LeonelListro commented
# Test Results

Tested locally on https://alexis-trackgenix-app-git-feature-tg-44-modal-2c20f2-basp-m2022.vercel.app/employees

**Test Results:** Failed ⚠️

### Bugs found:

1. Modal Succes should be smaller and title and message should be center.

![Sin título](https://user-images.githubusercontent.com/101256186/172951481-3edd79e6-0874-4428-a675-d0d0a1be33ae.png)
![Sin título](https://user-images.githubusercontent.com/101256186/172951778-99f00249-a2ff-48e1-b822-ab7aaf86f2d6.png)

2. The margin between the message and the buttons should be bigger and tittle should be centered.

![image](https://user-images.githubusercontent.com/101256186/172952674-5899e57a-48b6-4ab9-bcfb-6b019196e209.png)

3. (Suggestion) Add cross button to the top right of the modal.

![172952674-5899e57a-48b6-4ab9-bcfb-6b019196e209](https://user-images.githubusercontent.com/101256186/172953693-d4789216-655b-4d11-9966-4815b6987c82.png)

2022-06-09 22:10 UTC, LeonelListro requested changes
Refer to https://github.com/BaSP-m2022/alexis-trackgenix-app/pull/17#issuecomment-1151670576

2022-06-10 21:30 UTC, LeonelListro approved these changes

2022-06-11 19:20 UTC, merged