BaSP-TG-44: Shared Componentes Confirmation Modal
BaSP-m2022/alexis-trackgenix-app pull request #19
Opened 2022-06-08 02:20 UTC by lucianofrailelopez

Creation of modal for the confirmation of a deleted admin.

2022-06-08 02:54 UTC, agusting19 approved these changes
Looks nice buddy!

2022-06-08 14:21 UTC, Javier-Cervera requested changes

2022-06-08 14:42 UTC, iaracriscenti commented on src/Components/Shared/confirmationModal/confirmModal.module.css
> +    height: 50vh;
I agree with Javi here

2022-06-08 14:52 UTC, iaracriscenti commented on src/Components/Admins/Add/add.module.css
>    color: #000000;
It would be nice if the styles are relatable to Figma design or at least be similar to the other shared modals we created.

2022-06-08 16:10 UTC, NicolasFontana requested changes

2022-06-08 16:10 UTC, NicolasFontana commented on src/Components/Admins/Add/add.module.css
>    color: #000000;
I agree with Iara. Check out the timesheets delete modal which is quite similar to Figma

2022-06-09 16:06 UTC, Javier-Cervera approved these changes
Looks good!

2022-06-11 00:35 UTC, merged