BaSP-TG-26: Add/Edit Employee
BaSP-m2022/alexis-trackgenix-app pull request #2
Opened 2022-05-31 22:40 UTC by Javier-Cervera

Add done
Edit to do

2022-06-02 00:32 UTC, agusting19 commented on src/Components/Employees/SuccessModal/index.js
> +  console.log(props.message);
console.log

2022-06-02 00:33 UTC, agusting19 commented on src/Components/Employees/ListItem/ListItem.jsx
> +      console.error(error);
console.log

2022-06-02 00:36 UTC, agusting19 requested changes
The only thing to change is the fetch url and the console log's

2022-06-02 03:05 UTC, Javier-Cervera commented on src/Components/Employees/SuccessModal/index.js
> +  console.log(props.message);
Removed, thanks!

2022-06-02 03:06 UTC, Javier-Cervera commented on src/Components/Employees/ListItem/ListItem.jsx
> +      console.error(error);
Corresponds to TG-32

2022-06-02 12:27 UTC, agusting19 commented on src/Components/Employees/index.js
> +        console.log(response.data);
console.log

2022-06-02 12:28 UTC, agusting19 reviewed
Looks nice, only one missed console.log

2022-06-02 13:02 UTC, Javier-Cervera commented on src/Components/Employees/index.js
> +        console.log(response.data);
Thanks!

2022-06-03 12:34 UTC, tinchorova commented
Testing Results
Tested locally on https://alexis-trackgenix-app-git-feature-tg-26-add-e-c249ca-basp-m2022.vercel.app/employees

Test Results: Failed ⚠️

Bugs found:

**Add feature**
1. When creating a new employee, an error message pops up saying "active" must be a boolean even though "active" is selected. ![image](https://user-images.githubusercontent.com/101287875/171851625-ec41b116-0317-4182-8f43-896a7dcbc364.png)
2. The message in 1. is confusing for the user. The user shouldn't know what a boolean is.
3. Same problem going on with  PM boolean.
4. The only way I could create an employee was first selecting the boolean (Active and PM) that was not the default option.


**Edit feature**
6. When filling projects or timesheets with invalid data an error message pops up, this message is not understandable for the user 
![image](https://user-images.githubusercontent.com/101287875/171852638-e85372ce-84e7-41e2-845c-de7ffee3d7fc.png)
7. After succesfully edited an employee, it should redirect you to the list of employees, instead it stays in edit window (leaving employee updated message)
![image](https://user-images.githubusercontent.com/101287875/171852942-7b74b5ad-9e47-4115-a469-29ba57d0522a.png)

**PD:** Nice ticket!

2022-06-03 12:34 UTC, tinchorova requested changes
Please refer to: https://github.com/BaSP-m2022/alexis-trackgenix-app/pull/2#issuecomment-1145917899

2022-06-04 00:51 UTC, tinchorova approved these changes
Testing Results
Tested locally on https://alexis-trackgenix-app-git-feature-tg-26-add-e-c249ca-basp-m2022.vercel.app/employees

Test Results: approved!

⚠️ KEEP IN MIND: When opening edit or add modals, user shouldn't be allowed to scroll the page ⚠️

2022-06-04 03:21 UTC, merged