BaSP-TG-56: Employees shared components & redux
BaSP-m2022/alexis-trackgenix-app pull request #23
Opened 2022-06-15 01:24 UTC by Javier-Cervera

2022-06-15 19:31 UTC, agusting19 approved these changes
Nice buddy! It's working fine

2022-06-16 13:43 UTC, NicolasFontana approved these changes

2022-06-16 13:43 UTC, NicolasFontana commented on src/Components/Employees/Form/index.jsx
> +      dispatch(updateEmployee(userInput, item._id, (response) => setResponse(response))).then(
This is just a comment, this works fine!
Why do you pass this arrow function `(response) => setResponse(response)` as an argument to `createEmployee`, wouldn't it be more readable to pass `setResponse` to it?

`dispatch(createEmployee(userInput, setResponse))`

2022-06-17 22:49 UTC, tinchorova commented
## Testing results

Tested locally on: https://alexis-trackgenix-app-git-feature-tg-56-emplo-95386b-basp-m2022.vercel.app/employees

**Test result: Failed** ⚠️ 

bugs found:
1. Editing without making changes shouldn't be allowed, instead it shows a success message 
![image](https://user-images.githubusercontent.com/101287875/174408512-88141bc9-7f6b-4f61-a296-73ae21ec8bf3.png)
2. There is a bug with table's and footer's length, creating a blank space and a horizontal scrollbar
![image](https://user-images.githubusercontent.com/101287875/174408665-dd896a90-5291-4f0e-982a-1c22a8fa57fb.png)

2022-06-17 22:49 UTC, tinchorova requested changes
please refer to: https://github.com/BaSP-m2022/alexis-trackgenix-app/pull/23#issuecomment-1159288223

2022-06-18 15:19 UTC, tinchorova approved these changes
Good job!

2022-06-18 15:27 UTC, merged