BaSP-TG-59: Tasks shared components and redux
BaSP-m2022/alexis-trackgenix-app pull request #24
Opened 2022-06-15 01:57 UTC by agusting19

2022-06-16 02:53 UTC, Javier-Cervera commented on src/Components/Tasks/Form/Form.jsx
> +    console.log(`setShowMessage: ${setShowMessageModal}`);
console.log

2022-06-16 02:53 UTC, Javier-Cervera commented on src/Components/Tasks/Edit/Edit.jsx
> +    console.log(`setShowMessage: ${setShowMessageModal}`);
console.log

2022-06-16 02:53 UTC, Javier-Cervera commented on src/redux/tasks/thunks.js
> +        dispatch(addTaskSucces(response.data));
If we create a Task that doesn't pass validations, the page breaks.
In that case we could use a conditional so the dispatch isn't used
```
        if (response.error === false) {
          dispatch(addTaskSucces(response.data));
        }
```

2022-06-16 02:53 UTC, Javier-Cervera commented on src/redux/tasks/actions.js
> +export const addTaskSucces = (data) => ({
For consistency it should be written as "addTaskSuccess".
The same for all the rest

2022-06-16 02:53 UTC, Javier-Cervera commented on src/Components/Tasks/index.js
> +  return isLoading ? (
The page reloading with a modal open could be stopped using more conditions
```
 return isLoading &&
    !showModalFormEdit &&
    !showModalFormAdd &&
    !showMessageModal &&
    !showConfirmModal ?
```

2022-06-16 03:55 UTC, iaracriscenti approved these changes
Clean code and working good. Nice job!

2022-06-16 13:17 UTC, NicolasFontana approved these changes
Everything looks nice!

2022-06-18 00:10 UTC, ArianaMaldonado commented
Tested locally on: https://alexis-trackgenix-app-git-feature-tg-59-tasks-404db7-basp-m2022.vercel.app/

**Test Result: Failed ⚠️** 

Bugs found:
1. Delete modal needs more space for "Cancel" and "Delete" buttons. Also the "X" button/icon should be like the others: white and with no background as the example in the second picture.
![Screenshot from 2022-06-17 20-58-21](https://user-images.githubusercontent.com/101216228/174414018-40b81aec-89e0-4164-9634-580f67858b67.png)

![Screenshot from 2022-06-17 21-02-27](https://user-images.githubusercontent.com/101216228/174414067-80e89b69-3849-45c4-b0f1-e15cb301a5ad.png)

2. When adding a task with a longer description, the size of the table is changed. This shouldn't happen. _Maybe we can use a max-width?_

**Original table:**
![Screenshot from 2022-06-17 21-01-29](https://user-images.githubusercontent.com/101216228/174414214-47b85de7-5b30-4634-9b8d-b99a7dd75c95.png)

**Modified table:**
![Screenshot from 2022-06-17 21-08-55](https://user-images.githubusercontent.com/101216228/174414288-7b615c27-a6ca-4a5b-97e2-7dbfb0d12c42.png)

2022-06-18 00:11 UTC, ArianaMaldonado requested changes
Changes requested. Please, refer to https://github.com/BaSP-m2022/alexis-trackgenix-app/pull/24#issuecomment-1159313105

2022-06-19 00:07 UTC, ArianaMaldonado approved these changes
**Test Result: Approved.**
_Note: Changes requested to be fixed in "BaSP-TG-71: Fix shared components"._

2022-06-19 16:27 UTC, merged