BaSP-TG-54: Admins Shared component implementation & redux
BaSP-m2022/alexis-trackgenix-app pull request #26
Opened 2022-06-15 02:41 UTC by lucianofrailelopez

2022-06-16 14:09 UTC, NicolasFontana requested changes
Also, you should correct the size of the add and edit modal.
![image](https://user-images.githubusercontent.com/94578945/174088707-871262bf-b144-4da9-84cb-3d304a4c34cc.png)
![image](https://user-images.githubusercontent.com/94578945/174088768-c93d4c5c-384c-4671-92fd-e8c8abecea5c.png)

2022-06-16 14:18 UTC, agusting19 commented on src/Components/Admins/Edit/index.js
> +    // setEdited(true);
This comment can be deleted

2022-06-16 14:26 UTC, agusting19 reviewed
There are some commented lines to deleted and also problems with the esthetic. As Nico show us, the modal's need changes in the css, also, when we delete an Admin we never see the success.

2022-06-17 21:04 UTC, agusting19 reviewed
I saw that you were able to correct the css of the modal but there are still commented lines of code. Please review the corrections that were made to you

2022-06-18 17:47 UTC, NicolasFontana approved these changes
Nice work!

2022-06-19 16:28 UTC, agusting19 approved these changes
Nice work buddy!

2022-06-19 22:28 UTC, LeonelListro commented
# Testing Results

**Tested locally on:** https://alexis-trackgenix-app-git-feature-tg-63-share-0bd81f-basp-m2022.vercel.app/admins

Test result: Failed ⚠️

_Bugs found:_

1- Password should not be showed. 
![modal](https://user-images.githubusercontent.com/101256186/174502351-3278462e-60d1-401e-8676-2e0f8930c4dd.png)

2- When you submit whit an error data, the loader stays on the screen forever.
![modal](https://user-images.githubusercontent.com/101256186/174502412-97d55295-eddd-41e2-ae2c-2c9033372245.png)

3- The modal that appears at first is not the correct one.
![modal](https://user-images.githubusercontent.com/101256186/174502500-97be6df3-6795-4e33-92fb-7a20090d7ad2.png)

4- Modal should be centered in relation to the title.
![modal](https://user-images.githubusercontent.com/101256186/174502582-a662f553-6b3a-44ed-8605-ddb4578681a7.png)

## The above errors are repeated at all checkpoints.

2022-06-19 22:28 UTC, LeonelListro requested changes
Please refer to https://github.com/BaSP-m2022/alexis-trackgenix-app/pull/26#issuecomment-1159821736

2022-06-20 02:16 UTC, Javier-Cervera commented on src/Components/Shared/confirmationModal/confirmModal.module.css
> +    border: none;
Modal will be modified on another PR

2022-06-20 03:03 UTC, LeonelListro commented on src/Components/Shared/confirmationModal/confirmModal.module.css
> +    border: none;
Ok, should take in count the position of the delete modal too. (it's not centered taking in count the screen like others modals, and it should be).

2022-06-20 03:10 UTC, LeonelListro commented
Tested localy on: https://alexis-trackgenix-app-git-feature-tg-63-share-0bd81f-basp-m2022.vercel.app/admins

Previous corrections are approved ✔

New bugs found: ⚠

1- When you try to create a new admin with an invalid data on a field the error message modal deploy correctly, but if you try to close the error message modal and the add admin modal with the cross button, the page get crashed.

![image](https://user-images.githubusercontent.com/101256186/174518374-d8a6d5d5-02e8-433c-b508-719b1b117f0e.png)

2022-06-20 03:10 UTC, LeonelListro requested changes
New bugs found, please refer to https://github.com/BaSP-m2022/alexis-trackgenix-app/pull/26#issuecomment-1159918178

2022-06-20 22:05 UTC, LeonelListro approved these changes
Well done Luciano and team!

2022-06-20 22:16 UTC, merged