Feature tg 60 super admins shared components and redux
BaSP-m2022/alexis-trackgenix-app pull request #28
Opened 2022-06-15 02:47 UTC by Johsua30

2022-06-15 21:27 UTC, agusting19 commented on src/Components/Layout/index.js
> +// import SuperAdminsAdd from '../SuperAdmins/Form';
This can be deleted if is not used

2022-06-15 21:27 UTC, agusting19 commented on src/Components/Layout/index.js
> +        <Route exact path="/super-admins/edit" component={SuperAdminsEdit} /> */}
Same thing here. This can be deleted if is not used

2022-06-15 21:43 UTC, agusting19 commented on src/Components/SuperAdmins/Form/Edit.jsx
> +  // const [edited, setEdited] = useState(false);
This can be deleted if is not used

2022-06-15 21:44 UTC, agusting19 commented on src/Components/SuperAdmins/Form/Edit.jsx
> +    // setEdited(true);
This can be deleted if is not used

2022-06-15 21:44 UTC, agusting19 commented on src/Components/SuperAdmins/Form/Edit.jsx
> +    // setEdited(true);
Also this

2022-06-15 21:48 UTC, agusting19 reviewed
Looks good and it works. Only a few comment's to delete

2022-06-16 04:37 UTC, iaracriscenti commented on src/redux/super-admins/thunks.js
> +      setResponse(data);
If you open the add modal form, press the create button without entering any data, close the error modal and then close the add modal form, the page stays blocked with the preloader. I think this is because the last action dispatched is `postSuperAdminPending` that gives to `isLoading` a true value. A solution may be insert here a  `dispatch(postSuperAdminsError())` or `dispatch(getSuperAdmins())`, making sure that isLoading value is false. Let me know if that works!

2022-06-16 17:29 UTC, iaracriscenti approved these changes
Everything is working good now!

2022-06-16 23:23 UTC, agusting19 approved these changes
Nice and working!

2022-06-16 23:30 UTC, lucianofrailelopez approved these changes

2022-06-17 01:47 UTC, Javier-Cervera reviewed
Code and implementation looks good. It would be useful to test it with merges pulled

2022-06-18 00:46 UTC, LeonelListro commented
## Testing Results 

Tested locally on: https://alexis-trackgenix-app-git-feature-tg-60-super-47c4bc-basp-m2022.vercel.app/super-admins

Test result: _Failed_ ⚠️

**Bugs found:**

1- The Super-admin modals should be center.
![modal](https://user-images.githubusercontent.com/101256186/174414467-1ac86f56-7ec1-408b-954a-d1825296af46.png)

2- The modal should be wider, this way the title will fit on a single line.
![modal](https://user-images.githubusercontent.com/101256186/174414728-71b9a77b-633f-4e0e-957e-0e5d01f091de.png)

3- The create button should be right side and you should add a cancel button on the left side.
![modal](https://user-images.githubusercontent.com/101256186/174414858-8433ed36-5794-400f-93a0-515ae4fb0796.png)

4-  The "password" input should not show the password, it must be hidden.
![modal](https://user-images.githubusercontent.com/101256186/174415092-00529027-e597-4d12-ab71-acd0a09a74f8.png)

5- When you confirm the action in the modal appears a pre confirmation modal before the correct.
![modal](https://user-images.githubusercontent.com/101256186/174415345-e5189965-3374-4eac-ab14-006a9ef0cd4d.png)

## **1 to 5 errors are repeated in both modals**

6- The confirmation message when you edit without changing any data should be different.
![modal](https://user-images.githubusercontent.com/101256186/174415639-b333416f-74d6-409f-80d1-94710fb856f1.png)

2022-06-18 00:48 UTC, LeonelListro requested changes
Please refer to https://github.com/BaSP-m2022/alexis-trackgenix-app/pull/28#issuecomment-1159323510

2022-06-21 12:08 UTC, merged