BaSP-TG-25: List/Delete Projects
BaSP-m2022/alexis-trackgenix-app pull request #3
Opened 2022-05-31 23:56 UTC by LuliBianchini

2022-06-01 16:20 UTC, agusting19 commented on src/Components/Projects/ListItem/ListItem.jsx
> +      console.error(error);
console.log

2022-06-01 16:21 UTC, agusting19 commented on src/Components/Projects/index.js
> +  const [list, setProjects] = useState([]);
"list" can be "projects" to be more readable

2022-06-01 16:22 UTC, agusting19 submitted a review, later dismissed
You have to make little fixes

2022-06-02 21:54 UTC, tinchorova commented
## Testing results
Tested locally on https://alexis-trackgenix-app-git-feature-tg-25-list-60c4ba-basp-m2022.vercel.app/projects

**Test Results: Failed** ⚠️ 

Bugs found:

1. There should be a confirmation/cancel window when clicking a delete project button, instead it automatically deletes the project 
![image](https://user-images.githubusercontent.com/101287875/171744215-00ce5573-34f5-4b37-b889-a9c19b6e96bc.png)

2022-06-02 21:58 UTC, tinchorova requested changes
Please refer to https://github.com/BaSP-m2022/alexis-trackgenix-app/pull/3#issuecomment-1145381158

2022-06-03 18:52 UTC, tinchorova commented
Testing Results

Tested locally on https://alexis-trackgenix-app-git-feature-tg-27-list-78d848-basp-m2022.vercel.app/time-sheets

Test Results: Failed ⚠️

Bugs found:

1.When deleting a project, the delete modal is fixed and the user can interact with the rest of the page
![image](https://user-images.githubusercontent.com/101287875/171926853-94dcc747-0ddc-4ed9-8288-9abb76db0d6f.png)
-------------
![image](https://user-images.githubusercontent.com/101287875/171926961-47cffccd-f782-44a8-9270-e4a5d3415cbe.png)

2022-06-03 18:52 UTC, tinchorova requested changes
Please refer to: https://github.com/BaSP-m2022/alexis-trackgenix-app/pull/3#issuecomment-1146266938

2022-06-03 23:15 UTC, tinchorova commented
Testing Results

Tested locally on https://alexis-trackgenix-app-git-feature-tg-27-list-78d848-basp-m2022.vercel.app/time-sheets

Test Results: Failed ⚠️

Bugs found:
1. The problem was not fixed, user can still scroll up and down when modal is shown.

2022-06-03 23:37 UTC, tinchorova approved these changes
Testing Results

Tested locally on https://alexis-trackgenix-app-git-feature-tg-25-list-60c4ba-basp-m2022.vercel.app/projects
Test result: Approved!

**Keep in mid: User shouldn't be allowed to scroll while a modal is shown**

2022-06-04 00:09 UTC, iaracriscenti approved these changes

2022-06-04 00:10 UTC, merged