BaSP-TG-81: Update Project Forms
BaSP-m2022/alexis-trackgenix-app pull request #39
Opened 2022-06-22 02:12 UTC by AlejoGF

2022-06-24 14:06 UTC, LuliBianchini commented on src/Components/Admin/Projects/Form/AddMember/AddMember.jsx
> +  console.log('error', errors);
There's a console.log left in this line

2022-06-24 14:12 UTC, LuliBianchini commented on src/Components/Admin/Projects/Form/index.js
> +      setAlertMessage({ message: "There haven't been string changes", data: {}, error: true });
Maybe the message could be "There hasn't been any changes"?

2022-06-24 14:14 UTC, LuliBianchini commented on src/Components/Admin/Tasks/Edit/Edit.jsx
>          Cancel
This line can be erased since the button is labeled

2022-06-24 14:20 UTC, LuliBianchini reviewed
Everything is working and looking well! There are just a few things to delete

2022-06-24 14:22 UTC, LuliBianchini commented on src/Components/Admin/Tasks/Edit/Edit.jsx
>          Cancel
Just in case, I meant the "Cancel" below the button

2022-06-24 16:00 UTC, AlejoGF commented on src/Components/Admin/Tasks/Edit/Edit.jsx
>          Cancel
I didn't work on Admin components.

2022-06-24 16:52 UTC, Johsua30 commented on src/Components/Admin/Projects/Form/AddMember/AddMember.jsx
> +    console.log('data', data);
There's a console.log left in this line

2022-06-24 16:54 UTC, Johsua30 reviewed
A few messages should be changed but everything works fine

2022-06-24 19:41 UTC, LuliBianchini approved these changes
Everything looking good!

2022-06-24 19:52 UTC, NicolasFontana approved these changes
Everything looks good! Good work

2022-06-24 23:34 UTC, tinchorova commented
## Test results

Tested locally on: https://alexis-trackgenix-app-git-feature-tg-81-updat-7112f0-basp-m2022.vercel.app/admin/projects

**Test result: Failed** ⚠️ 

Bugs found:

**Add project**
1. UI bugs: Inputs should be equidistant to the sides. Create button outside of the form. The modal creates a scrollbar.
![image](https://user-images.githubusercontent.com/101287875/175721310-98bd2f33-02d2-4e3e-94e3-85e5fc2efe89.png)
2. There should be an 'on blur' event listener.
3. The invalid message shouldn't appear instantly when the user inputs a wrong data, (this is connected to point .2)
![image](https://user-images.githubusercontent.com/101287875/175721518-44068a5a-9998-4846-89a0-89ff7fea797d.png)
![image](https://user-images.githubusercontent.com/101287875/175721524-1372bf94-5ebd-4b93-9e22-a71710c97d5e.png)
4. There should be mores space between labels and messages
![image](https://user-images.githubusercontent.com/101287875/175721566-1a3dc721-f2fe-4ba0-b665-ca766e1001ef.png)
5. If end date is determined already, and an invalid start date is selected it does not show an error message on start date. The logic of this validation may cause you trouble.
![image](https://user-images.githubusercontent.com/101287875/175723582-c2d33957-8bf0-4785-875f-e79c1a2a4676.png)
![image](https://user-images.githubusercontent.com/101287875/175723890-27430442-7c09-4a9b-a8ab-b8918b430cc4.png)
![image](https://user-images.githubusercontent.com/101287875/175724263-0d929bc6-e638-428c-9b2a-3980f8270eb1.png)

**Edit project**
1. Invalid messages are changing the size of the form and moving the inputs
![image](https://user-images.githubusercontent.com/101287875/175733768-a4d059aa-3e59-4680-9b91-32da8fa2504b.png)
![image](https://user-images.githubusercontent.com/101287875/175734944-6019358b-317e-44d8-929a-233d7d079fb7.png)
2. Wording bug: 'rate' should have capital letter
![image](https://user-images.githubusercontent.com/101287875/175738094-b85bf2b8-80f8-4c14-8501-079c57e1b3b1.png)
3. There should be more space between labels and messages. Invalid messages are changing the size of the window(just a little bit)
![image](https://user-images.githubusercontent.com/101287875/175742899-7e295abf-3f5e-4011-a7af-b72574400f62.png)

2022-06-24 23:34 UTC, tinchorova requested changes
Please refer to: https://github.com/BaSP-m2022/alexis-trackgenix-app/pull/39#issuecomment-1166066330

2022-06-26 15:08 UTC, AlejoGF commented
Please do the tests in 1440x1024

2022-06-27 15:15 UTC, tinchorova approved these changes

2022-06-27 20:41 UTC, merged