BaSP-TG-27: List/Delete time-sheets
BaSP-m2022/alexis-trackgenix-app pull request #4
Opened 2022-06-01 00:40 UTC by NicolasFontana

2022-06-01 18:38 UTC, Javier-Cervera commented on src/Components/TimeSheets/index.js
> +      const response = await fetch(`${process.env.REACT_APP_API_URL}/api/time-sheets`);
Should be `${process.env.REACT_APP_API_URL}api/time-sheets`
without `/` before `api` because we'll deploy to `https://alexis-trackgenix-server.vercel.app/`
so we don't have `https://alexis-trackgenix-server.vercel.app//api/...`

2022-06-01 18:38 UTC, Javier-Cervera commented on src/Components/TimeSheets/index.js
> +      const response = await fetch(`${process.env.REACT_APP_API_URL}/api/time-sheets/${_id}`, {
Same as above

2022-06-01 18:38 UTC, Javier-Cervera commented on src/Components/TimeSheets/index.js
> +  return loading ? (
`loading ?` ?

2022-06-01 22:38 UTC, Javier-Cervera commented on src/Components/TimeSheets/index.js
> +      const response = await fetch(`${process.env.REACT_APP_API_URL}/api/time-sheets`);
Solved, the right resource is `https://alexis-trackgenix-server.vercel.app`

2022-06-01 22:38 UTC, Javier-Cervera commented on src/Components/TimeSheets/index.js
> +      const response = await fetch(`${process.env.REACT_APP_API_URL}/api/time-sheets/${_id}`, {
Solved, the right resource is `https://alexis-trackgenix-server.vercel.app`

2022-06-01 22:41 UTC, Javier-Cervera approved these changes
Looks good!

2022-06-03 00:33 UTC, tinchorova commented
Testing Results

Tested locally on https://alexis-trackgenix-app-git-feature-tg-27-list-78d848-basp-m2022.vercel.app/time-sheets

**Test Results: Failed** ⚠️

Bugs found:

1. Delete time-sheet confirmation window is asking to delete a super admin

![image](https://user-images.githubusercontent.com/101287875/171761035-8ecf346d-9992-4d18-b483-6917f65868aa.png)

2. Clicking "edit time-sheet" button is not redirecting to an edit window 
![image](https://user-images.githubusercontent.com/101287875/171762125-47a00ebc-b13e-47b1-bc86-fe6961875bf9.png)


3. "redireccionar a add" subtask on trello is marked as done but there is no button to add a time-sheet

4. (suggestion) you could add a tittle to the "succesfully deleted" message 
![image](https://user-images.githubusercontent.com/101287875/171762066-ba5a1632-f772-4493-9b91-f319ea549b13.png)

2022-06-03 00:34 UTC, tinchorova requested changes
Please refer to: https://github.com/BaSP-m2022/alexis-trackgenix-app/pull/4#issuecomment-1145472300

2022-06-03 18:37 UTC, tinchorova approved these changes
Testing Results:

Tested locally on https://alexis-trackgenix-app-git-feature-tg-27-list-78d848-basp-m2022.vercel.app/time-sheets

Test Results: Approved!

2022-06-03 19:14 UTC, merged