BaSP-TG-80: Update Employee Forms
BaSP-m2022/alexis-trackgenix-app pull request #40
Opened 2022-06-22 02:24 UTC by iaracriscenti

### Task's brief description:
Implement *React Hook Form* on Employee Add and Edit Forms to improve its operation and behavior, adding the validations to each type of input and making sure that the corresponding styles are seen.

2022-06-24 13:57 UTC, NicolasFontana requested changes

2022-06-24 13:57 UTC, NicolasFontana commented on src/Components/Admin/Employees/Form/index.jsx
> +      console.log(data);
Should delete this console.log

2022-06-24 13:57 UTC, NicolasFontana commented on src/Components/Admin/Employees/Form/index.jsx
> +        setResponse({ message: "There haven't been string changes", data: {}, error: true });
The user may not know what you mean by "string", I think "There haven't been any changes" is better.

2022-06-24 16:18 UTC, Johsua30 approved these changes
Messages and validations are looking good

2022-06-24 16:30 UTC, NicolasFontana approved these changes
Nice!

2022-06-24 22:59 UTC, tinchorova commented
## Test results
Tested locally on: https://alexis-trackgenix-app-git-feature-tg-80-updat-0e9869-basp-m2022.vercel.app/admin/employees

**Test results: Failed** ⚠️ 

bugs found: 
1. Validations should have an 'on blur' event listener
2. When writing an input, the required message is moving the inputs
![image](https://user-images.githubusercontent.com/101287875/175719250-8f9de8d8-016f-40ae-b1e1-bfd9a2db1650.png)
3. When the user focuses on an input to correct the data it should not be in red with the invalid message because he/she is trying to correct it.
![image](https://user-images.githubusercontent.com/101287875/175719603-3e4a2753-4120-4da7-b35c-ba097fdeede5.png)
4. The invalid message shouldn't appear instantly when the user inputs a wrong data, (this is connected to point 1.)
![image](https://user-images.githubusercontent.com/101287875/175719758-e50b99bd-84cf-4f52-8acf-f30604821bb2.png)
![image](https://user-images.githubusercontent.com/101287875/175719765-e63fe40e-4c6a-4e07-8aed-d3806e0e073d.png)
5. Point .4 applies here too. Invalid messages should change when 'on blur'
![image](https://user-images.githubusercontent.com/101287875/175720109-4e073508-c298-4728-9de2-a6372ac0e344.png)
![image](https://user-images.githubusercontent.com/101287875/175720135-1a881c39-25be-472b-b518-dedd06a18cdd.png)
6. Wrong validation on email, invalid input is taken as correct (it does not pass when clicking on edit button but there is no error message)
![image](https://user-images.githubusercontent.com/101287875/175720320-8ad9e9e7-e8f5-4411-aacd-ade6a5a5710a.png)
7. Why is an admin allowed to change employee's password?
![image](https://user-images.githubusercontent.com/101287875/175720512-848f333e-ec62-408b-9781-16c0ec7544b4.png)

2022-06-24 22:59 UTC, tinchorova requested changes
Please refer to: https://github.com/BaSP-m2022/alexis-trackgenix-app/pull/40#issuecomment-1166053779

2022-06-25 18:30 UTC, iaracriscenti commented
> Please refer to: [#40 (comment)](https://github.com/BaSP-m2022/alexis-trackgenix-app/pull/40#issuecomment-1166053779)

### BUGS:
- 1, 4, 5 *FIXED* --> changed useForm mode, now validations display  when on blur event occurs
- 2 *FIXED* --> changed modal form styles to allow more space
- 3 *FIXED* --> changed component on focus pseudo-class
- 6 *FIXED* --> changed email validation
- 7 *Will be taken into account in the coming weeks*

2022-06-25 23:42 UTC, tinchorova commented
## Test results
Tested locally on: https://alexis-trackgenix-app-git-feature-tg-80-updat-0e9869-basp-m2022.vercel.app/admin/employees

**Test results:** Approved, all functions are working, **but take this in count:**

bugs found:
1. When writing in password field the input moves
![image](https://user-images.githubusercontent.com/101287875/175793497-82122489-0c3b-4603-b9e1-875538fe740a.png)
![image](https://user-images.githubusercontent.com/101287875/175793502-afa86c8b-4240-407d-a8d5-3e0fcd23ecfd.png)
![image](https://user-images.githubusercontent.com/101287875/175793654-da92a6e2-136a-4b30-a70f-8981bae24507.png)

2022-06-25 23:43 UTC, tinchorova approved these changes
Good job! **important** please refer to https://github.com/BaSP-m2022/alexis-trackgenix-app/pull/40#issuecomment-1166379603

2022-06-26 15:41 UTC, merged