BaSP-TG-85: Update tasks forms
BaSP-m2022/alexis-trackgenix-app pull request #43
Opened 2022-06-22 02:47 UTC by LuliBianchini

2022-06-24 14:26 UTC, NicolasFontana requested changes

2022-06-24 14:26 UTC, NicolasFontana commented on src/Components/Tasks/Edit/Edit.jsx
> +    'any.required': 'Description is a required field'
For the correct message to be displayed you should change 'any.required' to 'string.empty'

2022-06-24 14:26 UTC, NicolasFontana commented on src/Components/Tasks/Edit/Edit.jsx
> +      'any.required': 'Status is a required field'
For the correct message to be displayed you should change 'any.required' to 'string.empty'

2022-06-24 14:26 UTC, NicolasFontana commented on src/Components/Tasks/Form/Form.jsx
> +});
You can copy and replace the task Schema with the fixes marked for the add method

2022-06-24 15:34 UTC, NicolasFontana requested changes

2022-06-24 15:34 UTC, NicolasFontana commented on src/Components/Tasks/Edit/Edit.jsx
> +      startDate: task.startDate,
When I click on edit, it does not load the date of that row

2022-06-24 15:34 UTC, NicolasFontana commented on src/Components/Tasks/Edit/Edit.jsx
> +  startDate: Joi.date().required().messages({ 'any.required': 'Start date is a required field' }),
You have to change `'any.required'` for this `'string.empty'`

2022-06-24 15:34 UTC, NicolasFontana commented on src/Components/Tasks/Form/Form.jsx
> +  startDate: Joi.date().required().messages({ 'any.required': 'Start date is a required field' }),
You have to change 'any.required' for this 'string.empty'

2022-06-24 15:34 UTC, NicolasFontana commented on src/Components/Tasks/Form/Form.jsx
> +      'string.empty': 'Status is a required field'
'string.empty' message is not working

2022-06-24 19:55 UTC, NicolasFontana approved these changes
Everything works well!

2022-06-24 20:57 UTC, LeonelListro commented
# Test results

Tested locally on: 

test result: **failed** ⚠️

## bugs found:

1- The task name field should allow be completed with numbers too.
![task name](https://user-images.githubusercontent.com/101256186/175665581-36a06298-8fd4-4259-8ac7-bc75f9adb43e.png)

2- The validation error message of the "Worked hours" field is the same when you let the empty field and when you fill it whit letters. 
![correct message](https://user-images.githubusercontent.com/101256186/175665807-c72015a1-b25f-4226-9589-0d5fcc3630bd.png)

2022-06-24 20:58 UTC, LeonelListro requested changes
Please refer to https://github.com/BaSP-m2022/alexis-trackgenix-app/pull/43#issuecomment-1165933104

2022-06-25 15:36 UTC, LeonelListro approved these changes
Well done Lucia and team!

2022-06-25 16:02 UTC, merged