BaSP-TG-32: List/Delete Employees
BaSP-m2022/alexis-trackgenix-app pull request #5
Opened 2022-06-01 01:33 UTC by LuliBianchini

2022-06-01 15:32 UTC, Javier-Cervera commented on src/Components/Employees/List/List.jsx
> +            <th> Projects </th>
Missing Timesheets

2022-06-01 23:00 UTC, NicolasFontana requested changes

2022-06-02 01:48 UTC, Javier-Cervera commented on src/Components/Employees/List/List.jsx
> +            <th> Projects </th>
Done next line

2022-06-02 03:14 UTC, Javier-Cervera approved these changes
Looks good, and works!

2022-06-02 19:38 UTC, NicolasFontana approved these changes

2022-06-02 19:49 UTC, NicolasFontana approved these changes

2022-06-03 17:11 UTC, ArianaMaldonado approved these changes

2022-06-03 17:50 UTC, merged