BaSP-TG-99: Superadmin flow
BaSP-m2022/alexis-trackgenix-app pull request #55
Opened 2022-07-05 16:13 UTC by Javier-Cervera

2022-07-06 20:50 UTC, iaracriscenti approved these changes
Everything works great! 🚀

2022-07-06 20:50 UTC, iaracriscenti commented on src/Components/SuperAdmin/Admins/index.jsx
> +          headers={['_id', 'firstName', 'lastName', 'email', 'active']}
Is it useful to show the id column?

2022-07-08 14:44 UTC, LeonelListro commented
# Test results

Tested locally on: https://alexis-trackgenix-app-git-feature-tg-99-super-25cd2c-basp-m2022.vercel.app/home

test result: failed ⚠️

bugs found:

1- The validation error message in the email input should be displayed.

![WhatsApp Image 2022-07-08 at 11 28 23 AM](https://user-images.githubusercontent.com/101256186/178013159-83deee2d-24d6-40fc-8444-f0fe007ada74.jpeg)

2- The box of the links in the sidebar should be smaller to facilitate their use. (The sector marked with a red oval is still part of admins link. The same happend with the log out link).

![Sin título](https://user-images.githubusercontent.com/101256186/178014416-2221ccee-33b2-4eee-9db8-32b6525b8177.png)

2022-07-08 14:45 UTC, LeonelListro requested changes
Tested failed. Please refer to https://github.com/BaSP-m2022/alexis-trackgenix-app/pull/55#issuecomment-1179069294

2022-07-09 02:07 UTC, LeonelListro approved these changes
Well done Javier and team! (It is noted that one of the bugs will be addressed in Ticket 108).

2022-07-09 02:10 UTC, merged