BaSP-TG-30: Tasks
BaSP-m2022/alexis-trackgenix-app pull request #6
Opened 2022-06-01 01:56 UTC by agusting19

2022-06-01 21:25 UTC, lucianofrailelopez approved these changes

2022-06-02 13:06 UTC, Javier-Cervera commented on src/Components/Tasks/List/List.jsx
> +          console.log(response);
console.log

2022-06-02 20:37 UTC, ArianaMaldonado commented
Tested locally on https://alexis-trackgenix-app-git-feature-tg-30tasks-agustin-basp-m2022.vercel.app/
**Test Results: Failed :warning:**

> Bugs found:

1. Date format is not clear, the user has to guess it. It should be better to use a date picker.
![Screenshot from 2022-06-02 17-13-21](https://user-images.githubusercontent.com/101216228/171731057-c18eaa6e-f32e-421d-b082-00f5fc4789bd.png)

2. When adding or editing a task successfully we should be redirected to the task list.
![Screenshot from 2022-06-02 17-28-49](https://user-images.githubusercontent.com/101216228/171732383-11638f12-a777-4b2a-ab74-61e6c83dac67.png)
![Screenshot from 2022-06-02 17-28-30](https://user-images.githubusercontent.com/101216228/171732371-ebd92574-3f20-48b0-aa07-ea4f55478558.png)

3. When editing a task and try to submit there is an error message, but we don't know where is the error.
![Screenshot from 2022-06-02 17-15-19](https://user-images.githubusercontent.com/101216228/171731170-832f6905-f09a-4081-9530-3592fe924ae9.png)

> Questions ❓ 

I can add/edit a task with decimal numbers, is that correct?
![Screenshot from 2022-06-02 17-33-02](https://user-images.githubusercontent.com/101216228/171733346-96e3129b-ec0c-499d-948c-7fc6fbf63307.png)

2022-06-02 20:40 UTC, ArianaMaldonado requested changes
Changes requested. Please, refer to https://github.com/BaSP-m2022/alexis-trackgenix-app/pull/6#issuecomment-1145317507

2022-06-03 17:15 UTC, ArianaMaldonado approved these changes

2022-06-03 17:18 UTC, merged