BaSP-TG-115: Responsive component's
BaSP-m2022/alexis-trackgenix-app pull request #65
Opened 2022-07-19 22:31 UTC by agusting19

2022-07-21 14:26 UTC, Javier-Cervera commented on src/Components/Shared/Table/table.module.css
> +  }
Only takes into account the data of an employee
(Worked Hours, Client Name, Start Date, etc?)

2022-07-21 15:24 UTC, Javier-Cervera reviewed
In `Components\Shared\ModalForm\modal-form.module.css`, on `.modal{ }` --> `max-width: 90vh;` could have a correct unit, like `vw`

In `Components\Admin\Projects\ProjectPage\MemberForm\memberForm.module.css`, on `.container{ }` --> `width: 20vw;` could be `width: unset;`

2022-07-21 15:24 UTC, Javier-Cervera commented on src/Components/Admin/Projects/ProjectPage/projectPage.module.css
>    margin: 10px;
On mobile --> `max-width: 90%` or `max-width: 90vw` could help with the border overflow

2022-07-23 17:48 UTC, NicolasFontana requested changes
When viewing the sidebar in mobile, the following happens:

![image](https://user-images.githubusercontent.com/94578945/180616829-33eb896e-f7fa-4d28-9572-fecc1d8b8282.png)


It would be nice if it went to the bottom of everything

2022-07-23 17:54 UTC, NicolasFontana requested changes
When the text is very long and there is a line break, the text is no longer centered

![image](https://user-images.githubusercontent.com/94578945/180617115-9917b64a-4832-4c89-b601-1d56b6bd5901.png)

2022-07-23 22:52 UTC, NicolasFontana approved these changes
Looks nice!

2022-07-25 22:05 UTC, LeonelListro commented
# Test Results

Tested localy on: https://alexis-trackgenix-app-git-feature-tg-115-resp-2554a4-basp-m2022.vercel.app/home

## Test results: Failed ⚠️

**Bugs found:**

**320*480 (Smartphone)**

1- The side bar is too big when it's displayed.

![image](https://user-images.githubusercontent.com/101256186/180877546-11f8e5e6-954a-4d6c-967e-638b769d548a.png)

2- The burger menu should be fixed on the screen (when you roll down de page the side bar go down too).

![Sin título](https://user-images.githubusercontent.com/101256186/180877779-16ce96e6-df25-4405-9c60-b97d01fa5c72.png)

3- In the login page there is no space between the main conteiner and the header and footer.

![Sin título](https://user-images.githubusercontent.com/101256186/180878026-c4cfe7fe-88d0-4cd7-add1-a38bfc2a946e.png)

4- In the employees admin table the delete button should be centered.

![Sin título](https://user-images.githubusercontent.com/101256186/180878555-8d49639f-aae4-4524-b8cf-5261260e5692.png)

5- In the projects admin table when you add new project, the modal is broken.

![image](https://user-images.githubusercontent.com/101256186/180878689-838148f3-dca5-4d35-8922-6afd29b3946f.png)

6- In the employee profile when you try to edit the profile, the modal is broken (do not show the title of the modal).

![image](https://user-images.githubusercontent.com/101256186/180878996-6bf4b587-9eac-404a-a152-3f8810031037.png)

7- In the super admin home the main title should be centered.

![image](https://user-images.githubusercontent.com/101256186/180879172-45679684-810f-47c6-88fd-ecc036d90f7b.png)

8- In the super admin admin table the elements should be centered.

![image](https://user-images.githubusercontent.com/101256186/180879270-cd492d63-6148-46b6-93c2-0713c2b04fe0.png)


**768*1023 (Tablet)**

1- The side bar is too big when it's displayed.

![image](https://user-images.githubusercontent.com/101256186/180879916-c13b4604-7f22-4c7b-8c59-9aced4a18fa3.png)

2- The wrong password modal should be centered.

![image](https://user-images.githubusercontent.com/101256186/180880163-d9f28ae3-707f-47f5-adf5-c5ecd25e6789.png)

3- The suggestion of user should not be there.

![Sin título](https://user-images.githubusercontent.com/101256186/180880471-7fe18be1-0866-48f8-85f7-363f38edcb27.png)


**1440*920 (Desktop)**

1- The suggestions of users should not be there.

![image](https://user-images.githubusercontent.com/101256186/180881040-9beb4cc7-3ed4-4e76-8678-dea1a46706b9.png)


**General bugs:**

1- When you try to add a new admin using an email address that is already in use the page crashes.

![image](https://user-images.githubusercontent.com/101256186/180881564-ed95490a-6871-477b-b2e8-d30ed0f5829c.png)

2022-07-25 22:06 UTC, LeonelListro requested changes
Test failed. Please refer to https://github.com/BaSP-m2022/alexis-trackgenix-app/pull/65#issuecomment-1194689381

2022-07-26 23:30 UTC, LeonelListro approved these changes
Well done Agustin and Team!

2022-07-27 13:13 UTC, merged