BaSP-TG-28: Admins.
BaSP-m2022/alexis-trackgenix-app pull request #9
Opened 2022-06-01 02:46 UTC by lucianofrailelopez

1. Show admin list.
2. Delete admin.
3. Add admin.
4. Edit admin.

2022-06-01 19:21 UTC, iaracriscenti reviewed
Some recommended changes to make.

2022-06-01 23:04 UTC, NicolasFontana requested changes

2022-06-01 23:04 UTC, NicolasFontana commented on src/Components/Admins/App.jsx
> +      const response = await fetch(`${process.env.REACT_APP_API_URL}api/admins`);
The right resource is https://alexis-trackgenix-server.vercel.app. Should put {process.env.REACT_APP_API_URL}/api/employees/${_id}

2022-06-01 23:04 UTC, NicolasFontana commented on src/Components/Admins/Edit/index.js
> +      const getAdmin = await fetch(`${process.env.REACT_APP_API_URL}api/admins/${adminID}`);
The right resource is https://alexis-trackgenix-server.vercel.app/. Should put {process.env.REACT_APP_API_URL}/api/employees/${_id}

2022-06-01 23:04 UTC, NicolasFontana commented on src/Components/Admins/Edit/index.js
> +    fetch(`${process.env.REACT_APP_API_URL}api/admins/${AdminID}`, {
The right resource is https://alexis-trackgenix-server.vercel.app. Should put {process.env.REACT_APP_API_URL}/api/employees/${_id}

2022-06-01 23:04 UTC, NicolasFontana commented on src/Components/Admins/App.jsx
> +      console.log('response', response);
console.log

2022-06-02 14:13 UTC, iaracriscenti approved these changes

2022-06-02 19:26 UTC, NicolasFontana approved these changes
🚀

2022-06-03 02:44 UTC, LeonelListro commented
## Testing Results
Tested locally on https://alexis-trackgenix-app-git-feature-tg-28admin-basp-m2022.vercel.app/

Test Results: Failed ⚠️

Bugs found:

1. The alert message depoyed when click delete icon is wrong, should be "Are you sure you want to delete this admin" and it says "Are you sure you want to delete this super admin".

![image](https://user-images.githubusercontent.com/101256186/171771553-5e63255c-03c7-49f0-8f5c-bd5d80f6c4e6.png)

2. This button should not exist, it has the same function of the cancel button.

![image](https://user-images.githubusercontent.com/101256186/171772185-ffa229b8-226e-46a2-ab71-76013a6ead83.png)

3. According to the convencions of "Material Design (https://material.io/)", the cancel button should be on left side, and the save button should be on the right side with a different text (could be "create").

![dsBuffer bmp](https://user-images.githubusercontent.com/101256186/171773201-abfa00d3-1857-4107-99e7-356227e7147c.png)

4. The active field is not required to create a new admin and it should be required.

![image](https://user-images.githubusercontent.com/101256186/171774402-307d8353-3ce7-4b27-8a7f-28bd98b1a3d2.png)

5. The delete text message should be "Admin deleted" and below "ID: number of id", no need for the ID to appear twice

![image](https://user-images.githubusercontent.com/101256186/171775511-c1ce19c9-8d70-4e68-998d-bc578bb8c25c.png)

6. The error message when you try to edit the name or/and the last name with numbers is difficult to understand because it shows a regex validation.

![image](https://user-images.githubusercontent.com/101256186/171776217-af138bfb-6743-48d6-b340-92c82e3ffa33.png)

2022-06-03 02:45 UTC, LeonelListro requested changes
Please refer to: https://github.com/BaSP-m2022/alexis-trackgenix-app/pull/9#issuecomment-1145531563

2022-06-03 11:17 UTC, AlexisPuchetaRR commented
Leeeendo testeo se mando Leo 👏

2022-06-03 20:16 UTC, LeonelListro approved these changes
Test Result: Approve 👍

2022-06-03 22:30 UTC, ArianaMaldonado commented
Tested locally on https://alexis-trackgenix-app-git-feature-tg-28admin-basp-m2022.vercel.app/

**Test Results: Failed :warning:**

Bugs found:
1. When creating/editing an Admin, we should be redirected to the Admin list again.
![Screenshot from 2022-06-03 19-05-57](https://user-images.githubusercontent.com/101216228/171962042-0894e6ca-4c99-44cb-9119-fbacdfdca184.png)

2. When we edit an Admin which 'Active' property is _true_, if we click on 'edit' without changing the _'Active'_ property, it changes to _false_ by default.
![Screenshot from 2022-06-03 19-14-41](https://user-images.githubusercontent.com/101216228/171962186-41787c44-bb99-4d68-bf70-411d5a5de4ec.png)
![Screenshot from 2022-06-03 19-17-59](https://user-images.githubusercontent.com/101216228/171962192-94d4249b-1aa2-4321-a7e9-487a8bbd0e18.png)

3. Wording bug. The message should be: 'Admin **deleted** ....'
![Screenshot from 2022-06-03 19-23-23](https://user-images.githubusercontent.com/101216228/171962306-9fb31106-555c-4dde-9b08-d3902061191a.png)

4. Should password be visible?
![Screenshot from 2022-06-03 19-28-38](https://user-images.githubusercontent.com/101216228/171962450-b8d692b5-1b86-4571-aec8-02a3ae25d77c.png)

2022-06-03 22:30 UTC, ArianaMaldonado requested changes
Changes requested. Please, refer to https://github.com/BaSP-m2022/alexis-trackgenix-app/pull/9#issuecomment-1146414215

2022-06-04 01:29 UTC, ArianaMaldonado approved these changes

2022-06-04 17:32 UTC, merged